# This is a basic workflow to help you get started with Actions

name: Generate List

# Controls when the workflow will run
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 15 * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.6'

      - name: Install requirements
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt

      - name: Execute script
        run: python3 src/mingo/main.py -o && ls

      - name: Release language list
        uses: djnicholson/release-action@v2.10
        with:
          token: ${{ secrets.TOKEN }}
          asset-name: 'languages.json'
          release-name: ${{ github.sha }}
          file: 'languages.json'
